### ISSUE TITLE
update R vignettes

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/DALEX-docs#43]
please

**Comment by kozaka93** [comment]
- [ ] Comparison between breakdown, lime, shapley
- [ ] DALEX_and_keras
- [ ] DALEX_and_xgboost
- [ ] DALEX_caret
- [ ] DALEX_h2o
- [ ] DALEX_mlr
- [ ] DALEX_parsnip
- [ ] DALEX_teaching
- [ ] DALEX_teaching2
- [ ] DALEXverse and fraud detection
- [ ] How-to-use-DALEXtra-to-explain-and-visualize-scikitlearn-models
- [ ] Multilanguages_comparision

**Comment by hbaniecki** [comment]
@kozaka93 @jakwisn are there any vignettes left/could I help or it should be closed?

**Comment by kozaka93** [comment]
There are two more items on the list, but I don't have the environment to reproduce them.

**Comment by hbaniecki** [comment]
Indeed, `DALEXverse and fraud detection` seems irreproducible.

**Comment by hbaniecki** [comment]
As for `How-to-use-DALEXtra-to-explain-and-visualize-scikitlearn-models`, it seems out of my capabilities either.

**Comment by hbaniecki** [comment]
Thanks!
